spring:
  cloud:
    stream:
      default:
        contentType: application/json
        consumer:
          maxAttempts: 3
      bindings:
        myInput:
          consumer:
            concurrency: 1
          destination: temp-queue1
          group: rabbit-receiver1
      rabbit:
        bindings:
          myInput:
            consumer:
              exchangeType: fanout

